version: "3"

services:
    backend:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      ports:
          - 3000:3000
          - 9229:9229
      volumes:
          - ../:/home/node/app
      command: npm run serve